/** @type {import('prettier').Config & import('prettier-plugin-tailwindcss').PluginOptions} */
const config = {
  plugins: ['prettier-plugin-tailwindcss', '@trivago/prettier-plugin-sort-imports'],
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: true,
  trailingComma: 'es5',
  bracketSpacing: true,
  arrowParens: 'always',
  importOrder: [
    '^server-only',
    '^next',
    '^react',
    '^react-hook-form',
    '^@trpc/server',
    '^superjson',
    '^kysely',
    '^sonner',
    '^xlsx',
    '^zod',
    '^lucide-react',
    '^@tanstack',
    '^dayjs',
    'class-variance-authority',
    '^@hookform/resolvers/zod',
    '^@/trpc/*',
    '^@/hooks/*',
    '^@/schemas/*',
    '^@/app/*',
    '^@/components/*',
    '^@/lib/*',
    '^@/styles/*',
    '^[./]',
    '^.*\\.css$',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
}

export default config
