import { TRPCReactProvider } from '@/trpc/react'

import { type Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import { type ReactNode } from 'react'

import { Toaster } from '@/components/ui/sonner'

import { cn } from '@/lib/utils'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

type RootLayoutPropsType = Readonly<{
  children: ReactNode
}>

const RootLayout = ({ children }: RootLayoutPropsType) => {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  )
}

export default RootLayout
